/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export type AirdropInfoStruct = {
  airdropName: string;
  airdropAddress: AddressLike;
  totalAirdropAmount: BigNumberish;
  airdropAmountLeft: BigNumberish;
  claimAmount: BigNumberish;
  expirationDate: BigNumberish;
  airdropType: BigNumberish;
};

export type AirdropInfoStructOutput = [
  airdropName: string,
  airdropAddress: string,
  totalAirdropAmount: bigint,
  airdropAmountLeft: bigint,
  claimAmount: bigint,
  expirationDate: bigint,
  airdropType: bigint
] & {
  airdropName: string;
  airdropAddress: string;
  totalAirdropAmount: bigint;
  airdropAmountLeft: bigint;
  claimAmount: bigint;
  expirationDate: bigint;
  airdropType: bigint;
};

export interface AirdropManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "addAirdrop"
      | "allowAddress"
      | "allowAddresses"
      | "claim"
      | "claimCustom"
      | "disallowAddress"
      | "disallowAddresses"
      | "getAdminCount"
      | "getAirdropAmountLeft"
      | "getAirdropInfo"
      | "getAirdrops"
      | "getBalance"
      | "getClaimAmount"
      | "getExpirationDate"
      | "getTotalAirdropAmount"
      | "hasClaimed"
      | "hasExpired"
      | "isAdmin"
      | "isAllowed"
      | "owner"
      | "removeAdmin"
      | "removeAirdrop"
      | "renounceOwnership"
      | "setRoot"
      | "transferAdminOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressAllowedByManager"
      | "AddressDisallowedByManager"
      | "AdminAdded"
      | "AdminRemoved"
      | "AirdropAdded"
      | "AirdropRemoved"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAirdrop",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowAddress",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "allowAddresses",
    values: [AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claim",
    values: [AddressLike, AddressLike, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCustom",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disallowAddress",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "disallowAddresses",
    values: [AddressLike, AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getAdminCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAirdropAmountLeft",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAirdropInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAirdrops",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExpirationDate",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalAirdropAmount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasClaimed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasExpired",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isAllowed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAirdrop",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setRoot",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferAdminOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addAirdrop", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "allowAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "allowAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimCustom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disallowAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disallowAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAdminCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAirdropAmountLeft",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAirdropInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAirdrops",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExpirationDate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalAirdropAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasClaimed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasExpired", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAdmin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAllowed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAirdrop",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setRoot", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferAdminOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AddressAllowedByManagerEvent {
  export type InputTuple = [
    airdropAddress: AddressLike,
    user: AddressLike,
    allowedBy: AddressLike
  ];
  export type OutputTuple = [
    airdropAddress: string,
    user: string,
    allowedBy: string
  ];
  export interface OutputObject {
    airdropAddress: string;
    user: string;
    allowedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddressDisallowedByManagerEvent {
  export type InputTuple = [
    airdropAddress: AddressLike,
    user: AddressLike,
    disallowedBy: AddressLike
  ];
  export type OutputTuple = [
    airdropAddress: string,
    user: string,
    disallowedBy: string
  ];
  export interface OutputObject {
    airdropAddress: string;
    user: string;
    disallowedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminAddedEvent {
  export type InputTuple = [admin: AddressLike, addedBy: AddressLike];
  export type OutputTuple = [admin: string, addedBy: string];
  export interface OutputObject {
    admin: string;
    addedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AdminRemovedEvent {
  export type InputTuple = [admin: AddressLike, removedBy: AddressLike];
  export type OutputTuple = [admin: string, removedBy: string];
  export interface OutputObject {
    admin: string;
    removedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AirdropAddedEvent {
  export type InputTuple = [airdropAddress: AddressLike];
  export type OutputTuple = [airdropAddress: string];
  export interface OutputObject {
    airdropAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AirdropRemovedEvent {
  export type InputTuple = [airdropAddress: AddressLike];
  export type OutputTuple = [airdropAddress: string];
  export interface OutputObject {
    airdropAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AirdropManager extends BaseContract {
  connect(runner?: ContractRunner | null): AirdropManager;
  waitForDeployment(): Promise<this>;

  interface: AirdropManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;

  addAirdrop: TypedContractMethod<
    [newAirdropAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  allowAddress: TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;

  allowAddresses: TypedContractMethod<
    [airdropAddress: AddressLike, users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  claim: TypedContractMethod<
    [
      airdropAddress: AddressLike,
      user: AddressLike,
      amount: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  claimCustom: TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;

  disallowAddress: TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;

  disallowAddresses: TypedContractMethod<
    [airdropAddress: AddressLike, users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  getAdminCount: TypedContractMethod<[], [bigint], "view">;

  getAirdropAmountLeft: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  getAirdropInfo: TypedContractMethod<
    [airdropAddress: AddressLike],
    [AirdropInfoStructOutput],
    "view"
  >;

  getAirdrops: TypedContractMethod<[], [string[]], "view">;

  getBalance: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  getClaimAmount: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  getExpirationDate: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  getTotalAirdropAmount: TypedContractMethod<
    [airdropAddress: AddressLike],
    [bigint],
    "view"
  >;

  hasClaimed: TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;

  hasExpired: TypedContractMethod<
    [airdropAddress: AddressLike],
    [boolean],
    "view"
  >;

  isAdmin: TypedContractMethod<[_address: AddressLike], [boolean], "view">;

  isAllowed: TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeAdmin: TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;

  removeAirdrop: TypedContractMethod<
    [airdropAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setRoot: TypedContractMethod<
    [airdropAddress: AddressLike, _root: BytesLike],
    [void],
    "nonpayable"
  >;

  transferAdminOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[_newAdmin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addAirdrop"
  ): TypedContractMethod<
    [newAirdropAddress: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowAddress"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "allowAddresses"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, users: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      airdropAddress: AddressLike,
      user: AddressLike,
      amount: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimCustom"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disallowAddress"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disallowAddresses"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, users: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAdminCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAirdropAmountLeft"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAirdropInfo"
  ): TypedContractMethod<
    [airdropAddress: AddressLike],
    [AirdropInfoStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAirdrops"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getClaimAmount"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getExpirationDate"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalAirdropAmount"
  ): TypedContractMethod<[airdropAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "hasClaimed"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasExpired"
  ): TypedContractMethod<[airdropAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAdmin"
  ): TypedContractMethod<[_address: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isAllowed"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeAirdrop"
  ): TypedContractMethod<[airdropAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRoot"
  ): TypedContractMethod<
    [airdropAddress: AddressLike, _root: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferAdminOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AddressAllowedByManager"
  ): TypedContractEvent<
    AddressAllowedByManagerEvent.InputTuple,
    AddressAllowedByManagerEvent.OutputTuple,
    AddressAllowedByManagerEvent.OutputObject
  >;
  getEvent(
    key: "AddressDisallowedByManager"
  ): TypedContractEvent<
    AddressDisallowedByManagerEvent.InputTuple,
    AddressDisallowedByManagerEvent.OutputTuple,
    AddressDisallowedByManagerEvent.OutputObject
  >;
  getEvent(
    key: "AdminAdded"
  ): TypedContractEvent<
    AdminAddedEvent.InputTuple,
    AdminAddedEvent.OutputTuple,
    AdminAddedEvent.OutputObject
  >;
  getEvent(
    key: "AdminRemoved"
  ): TypedContractEvent<
    AdminRemovedEvent.InputTuple,
    AdminRemovedEvent.OutputTuple,
    AdminRemovedEvent.OutputObject
  >;
  getEvent(
    key: "AirdropAdded"
  ): TypedContractEvent<
    AirdropAddedEvent.InputTuple,
    AirdropAddedEvent.OutputTuple,
    AirdropAddedEvent.OutputObject
  >;
  getEvent(
    key: "AirdropRemoved"
  ): TypedContractEvent<
    AirdropRemovedEvent.InputTuple,
    AirdropRemovedEvent.OutputTuple,
    AirdropRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AddressAllowedByManager(address,address,address)": TypedContractEvent<
      AddressAllowedByManagerEvent.InputTuple,
      AddressAllowedByManagerEvent.OutputTuple,
      AddressAllowedByManagerEvent.OutputObject
    >;
    AddressAllowedByManager: TypedContractEvent<
      AddressAllowedByManagerEvent.InputTuple,
      AddressAllowedByManagerEvent.OutputTuple,
      AddressAllowedByManagerEvent.OutputObject
    >;

    "AddressDisallowedByManager(address,address,address)": TypedContractEvent<
      AddressDisallowedByManagerEvent.InputTuple,
      AddressDisallowedByManagerEvent.OutputTuple,
      AddressDisallowedByManagerEvent.OutputObject
    >;
    AddressDisallowedByManager: TypedContractEvent<
      AddressDisallowedByManagerEvent.InputTuple,
      AddressDisallowedByManagerEvent.OutputTuple,
      AddressDisallowedByManagerEvent.OutputObject
    >;

    "AdminAdded(address,address)": TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;
    AdminAdded: TypedContractEvent<
      AdminAddedEvent.InputTuple,
      AdminAddedEvent.OutputTuple,
      AdminAddedEvent.OutputObject
    >;

    "AdminRemoved(address,address)": TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;
    AdminRemoved: TypedContractEvent<
      AdminRemovedEvent.InputTuple,
      AdminRemovedEvent.OutputTuple,
      AdminRemovedEvent.OutputObject
    >;

    "AirdropAdded(address)": TypedContractEvent<
      AirdropAddedEvent.InputTuple,
      AirdropAddedEvent.OutputTuple,
      AirdropAddedEvent.OutputObject
    >;
    AirdropAdded: TypedContractEvent<
      AirdropAddedEvent.InputTuple,
      AirdropAddedEvent.OutputTuple,
      AirdropAddedEvent.OutputObject
    >;

    "AirdropRemoved(address)": TypedContractEvent<
      AirdropRemovedEvent.InputTuple,
      AirdropRemovedEvent.OutputTuple,
      AirdropRemovedEvent.OutputObject
    >;
    AirdropRemoved: TypedContractEvent<
      AirdropRemovedEvent.InputTuple,
      AirdropRemovedEvent.OutputTuple,
      AirdropRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
