/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AirdropManager } from "./AirdropManager";
export type { ICustomAirdrop } from "./ICustomAirdrop";
export type { IMerkleAirdrop } from "./IMerkleAirdrop";
